train_data_path: "data/train.csv"
test_data_path: "data/test.csv"

model_dump_path: "models/model.bin"
column_dump_path: "models/columns.bin"

predict_report_path: "reports/titanic_predictions.csv"

train_params:
  model_type: "RandomForestClassifier"
  criterion: "entropy"
  n_estimators: 700
  min_samples_split: 10
  min_samples_leaf: 1
  max_features: "auto"
  oob_score: True
  random_state: 1
  n_jobs: -1

model_api_port: 5555