version: '3.2'
services:
  titanic-model:
    build: 
      context: .
      cache_from:
        - python:3.8-slim
    image: otus-de-hw8:1.0
    container_name: titanic-model
    environment:
      - BACKEND_HOST=titanic-model
    command: python /opt/titanic_model/titanic_model.py serve /opt/titanic_model/configs/model_config.yaml
    restart: always
    ports:
      - "${MODEL_API_PORT}:${MODEL_API_PORT}"

